# Generated by Django 3.2.3 on 2021-05-16 12:11

import banking.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_remove_transaction_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, 'ENABLED'), (2, 'DISABLED'), (3, 'DELETED'), (4, 'PROFORMA'), (5, 'PENDING')], default=banking.helper.AccountStatuses['ENABLED']),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creditDebitIndicator',
            field=models.IntegerField(choices=[(1, 'CREDIT'), (2, 'DEBIT')], default=banking.helper.CreditDebitCodes['CREDIT']),
        ),
    ]
